name: Security Checks
on:
  push:
    branches:
          - test 
jobs:
  login:
    name: TFSEC_Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'


  swap-jobs:
    name: swap environment
    needs: login
    runs-on: ubuntu-latest
    steps:
      - name: 'swap'
        run: |
            az login
            az functionapp deployment slot swap -g ibinder -n ibinderApp --slot Staging 
 
            
