name: Security Checks
on:
  push:
    branches:
          - test 
jobs:
  login:
    name: TFSEC_Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: dick
        run: |
            az login
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          run: |
            az functionapp deployment slot swap -g ibinder -n ibinderApp --slot Staging 
 