name: Security Checks
on:
  push:
    branches:
          - test 
jobs:
  login:
    name: TFSEC_Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: login
        uses: azure/login@v1
        with:
          github_token: ${{ github.token }}


  swap-jobs:
    name: swap environment
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
   