name: Provision infrastructure
on:
  push:
    branches:
          - infra
jobs:
  tfsec:
    name: Check Terraform Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
  
  provision-infra:
    name: Provision infrastructure
    needs: tfsec
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CLIENT_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'terraform import azurerm_storage_account.issuereporting /subscriptions/***/resourceGroups/ibinder/providers/Microsoft.Storage/storageAccounts/customeruserstorage'
          tf_actions_working_dir: "./terraform"
