on:
  push:
    branches:
          - test 

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

  swap-staging-production:
    name: Final_job
    needs: login
    runs-on: ubuntu-latest
    steps:
      - run: | 
              az functionapp deployment slot swap -g ibinder -n ibinderApp --slot Staging 

