on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

  cd-swap-staging-production:
    name: Final_job
    runs-on: ubuntu-latest
    steps:
      - run: | 
              az functionapp deployment slot swap -g ibinder -n ibinderApp --slot Staging 

