name: CI-CD Pipline
on:
  push:
    branches:
          - develop
          - test
          - main 
jobs:
  cd-build-deploy-development:
    name: Provision infrastructure Build and Deploy - Development
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/develop'
    env:
      AZURE_FUNCTIONAPP_NAME: development
      AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
      DOTNET_VERSION: '6.0.x' 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.MVP_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      Terraform_Path: './terraform'
      
    steps:
      - name: 'Terraform init'
        id: init
        run: |
          terraform init

      - name: 'Terraform plan'
        id: plan
        run: |
          terraform plan
          
      - name: 'Terraform apply'
        id: apply
        run: |
          terraform apply -auto-approve