on:
  push:
    branches:
          - test 

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: login and swap 
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          run: | 
              az login

        
