on:
  push:
    branches:
          - test 

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: login 
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          run: | 
              az login
  
  swap:
    - name: swap-job
    

              az functionapp deployment slot swap -g ibinder -n ibinderApp --slot Staging 



        
